import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials',
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Components',
      items: [
        {
          type: 'autogenerated',
          dirName: 'components',
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        },
      ],
    },
    {
      type: 'category',
      label: 'Support',
      items: [
        {
          type: 'autogenerated',
          dirName: 'support',
        },
      ],
    },
  ],

  typedocSidebar: [
    {
      type: 'category',
      label: '@tremolo-ui/functions',
      link: {
        type: 'doc',
        id: 'api/functions/index',
      },
      items: require('./docs/api/functions/typedoc-sidebar.cjs'),
    },
    {
      type: 'category',
      label: '@tremolo-ui/react',
      link: {
        type: 'doc',
        id: 'api/react/index',
      },
      items: require('./docs/api/react/typedoc-sidebar.cjs'),
    },
  ],
}

export default sidebars
