import typedocSidebarDom from './docs/api/dom/typedoc-sidebar.cjs'
import typedocSidebarFunctions from './docs/api/functions/typedoc-sidebar.cjs'
import typedocSidebarReact from './docs/api/react/typedoc-sidebar.cjs'

import type {
  SidebarsConfig,
  SidebarItemConfig,
} from '@docusaurus/plugin-content-docs'

/**
 * Give every generated item a translation key of its own.
 *
 * Docusaurus builds the key from the label, and typedoc labels a page with the
 * last segment of its module path. Those collide across the one sidebar —
 * `piano` is a module of both `@tremolo-ui/functions` and `@tremolo-ui/dom`,
 * and `input` appears twice within `dom` alone — and a collision fails the
 * build. Doc ids are already unique, so they make the keys.
 */
function withKeys(
  items: SidebarItemConfig[],
  prefix: string,
): SidebarItemConfig[] {
  return items.map((item) => {
    if (typeof item === 'string') return item
    if (item.type === 'category') {
      const key = `${prefix}.${item.label}`
      return { ...item, key, items: withKeys(item.items, key) }
    }
    if (item.type === 'doc') {
      return { ...item, key: item.id }
    }
    return item
  })
}

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials',
        },
      ],
    },
    {
      type: 'category',
      label: 'Components',
      link: {
        type: 'generated-index',
        title: 'Components',
        keywords: ['components'],
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'components',
        },
      ],
    },
    {
      type: 'category',
      label: 'Hooks',
      items: [
        {
          type: 'autogenerated',
          dirName: 'hooks',
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        },
      ],
    },
    {
      type: 'category',
      label: 'Changelog',
      // The intro is the category's own page, so the label is the link to it
      // and sits at the top of the group.
      link: {
        type: 'doc',
        id: 'changelog/index',
      },
      // Listed one by one rather than autogenerated. `autogenerated` does not
      // leave out the doc the category links to — only a category the
      // generator builds from a folder itself gets that treatment — so
      // `changelog/index` came out a second time at the end of the list.
      //
      // The per-package pages are generated by `site/scripts/changelog.mjs`,
      // which has the same list of packages. Both change together.
      items: ['changelog/functions', 'changelog/dom', 'changelog/react'],
    },
  ],

  typedocSidebar: [
    {
      type: 'category',
      label: '@tremolo-ui/functions',
      link: {
        type: 'doc',
        id: 'api/functions/index',
      },
      items: withKeys(typedocSidebarFunctions, 'functions'),
    },
    {
      type: 'category',
      label: '@tremolo-ui/dom',
      link: {
        type: 'doc',
        id: 'api/dom/index',
      },
      items: withKeys(typedocSidebarDom, 'dom'),
    },
    {
      type: 'category',
      label: '@tremolo-ui/react',
      link: {
        type: 'doc',
        id: 'api/react/index',
      },
      items: withKeys(typedocSidebarReact, 'react'),
    },
  ],
}

export default sidebars
