# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: test & package build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Setup safe-chain
      run: |
        npm i -g @aikidosec/safe-chain
        safe-chain setup-ci

    - name: Install dependencies
      run: npm ci

    - name: Test (packages/function)
      run: npm run test -w packages/functions
    - name: Build (packages/function)
      run: npm run build:package -w packages/functions

    - name: Test (packages/react)
      run: npm run test -w packages/react
    - name: Build (packages/react)
      run: npm run build:package -w packages/react
