name: Release alpha version package

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'

    - name: Setup safe-chain
      run: |
        npm i -g @aikidosec/safe-chain
        safe-chain setup-ci

    - name: Install dependencies
      run: npm ci

    - name: Test (packages/function)
      run: npm run test -w packages/functions
    - name: Build (packages/function)
      run: npm run build:package -w packages/functions

    - name: Test (packages/react)
      run: npm run test -w packages/react
    - name: Build (packages/react)
      run: npm run build:package -w packages/react

    - name: Publish (packages/functions)
      run: npm publish --tag alpha --provenance -w packages/functions
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Publish (packages/react)
      run: npm publish --tag alpha --provenance -w packages/react
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
